# Generated by Django 5.2.4 on 2025-07-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpcStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('class_text', models.CharField(max_length=200)),
                ('health_int', models.IntegerField()),
                ('weapons_text', models.CharField()),
                ('cyberware_text', models.CharField()),
                ('cooldowns_bool', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Cooldowns',
        ),
        migrations.DeleteModel(
            name='Cyberware',
        ),
        migrations.DeleteModel(
            name='Health',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Weapons',
        ),
    ]
